#!/usr/bin/env ruby

require 'colorize'
require 'sqlite3'

output = %x(free -tom)

#puts output.to_s

lines = output.split(/\n/)

t = Time.new
mem = Hash.new
swap = Hash.new
lines.each do |line|
	store = line.split(" ")[0]
	case store 
	when 'total'
		next
	when "Mem:"
		mem[:used] = line.split(" ")[2]
		mem[:free] = line.split(" ")[3]
	when "Swap:"
		swap[:used] = line.split(" ")[2]
		swap[:free] = line.split(" ")[3]
	end 
	#puts stoore.to_s.green
end

dbdate = "#{t.year}-#{t.month}-#{t.day} #{t.hour}:#{t.min}:#{t.sec}"
puts "#{dbdate}, #{mem[:used]}, #{swap[:used]}"

begin
	db = SQLite3::Database.open("/var/www/localhost/htdocs/db/mem.db")
	db.execute("CREATE TABLE IF NOT EXISTS mem(id INTEGER PRIMARY KEY AUTOINCREMENT, date DATETIME, mem_used INTEGER, swap_used INTEGER)")
	db.execute("INSERT INTO mem (date, mem_used, swap_used) VALUES ('#{dbdate}','#{mem[:used]}','#{swap[:used]}')")
rescue SQLite3::Exception => e
	puts "Exception occurred: #{e.message}".red
ensure
	db.close if db
end
